name: Luacheck
on: [push, pull_request]
jobs:
  Luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update repositories
        run: sudo apt update
      - name: Install Luacheck
        uses: ./.github/workflows/actions/cache-apt-pkgs-action
        with:
          packages: lua-check
      - name: Luacheck linter
        run: luacheck --config .luacheckrc .
