name: StyLua
on: [push, pull_request]
jobs:
  StyLuacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: StyLua check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          version: v0.18.2 # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: --check .
