name: StyLua
on: [push, pull_request]
jobs:
  StyLuacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-hack from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: stylua
          version: 0.20.0

      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code formatting
        run: stylua -c .
