name: StyLua
on: [push, pull_request]
jobs:
  StyLua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update repositories
        run: sudo apt update
      - name: Install cargo
        uses: ./.github/workflows/actions/cache-apt-pkgs-action
        with:
          packages: cargo libssh2-1

      - name: Install StyLua from crates.io
        uses: ./.github/workflows/actions/cargo-install
        with:
          crate: stylua
          version: 0.20.0

      - name: Check code formatting
        run: stylua -c .
